services:
  klausur:
    image: webt-klausur
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 4200
        published: 4200
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp